services:
  ghost:
    image: ghost:5-alpine
    container_name: notes-ghost
    restart: always
    ports:
      - 2368:2368
    environment:
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      url: http://localhost:2368
    volumes:
      - ghost:/var/lib/ghost/content

volumes:
  ghost:
